### PR TITLE
Bump runtime to 21.08

### PR DESCRIPTION
**Pull request by bbhtt**
cc @matfantinel Please review when you have time. Thanks!

2.3.0 builds fine but doesn't launch, so I kept it at 2.2.0:

```
** (com.github.matfantinel.moneta:2): CRITICAL **: 07:10:06.601: Settings.vala:87: Could not connect: No such file or directory

** (com.github.matfantinel.moneta:2): CRITICAL **: 07:10:06.601: Settings.vala:107: Could not connect: No such file or directory
```

### CODE REVIEW

**Comment by matfantinel** [comment]
Hi @bbhtt ! Thanks for the PR!

I'm not running Linux anymore, so it's a bit hard to check if it's working correctly. I'll just to check if there's anything else I have to do on the app's own repo before I merge this.

**Comment by bbhtt** [comment]
Sure, thank you!

**Comment by bbhtt** [comment]
> I'm not running Linux anymore, so it's a bit hard to check if it's working correctly. I'll just to check if there's anything else I have to do on the app's own repo before I merge this.

Hey, did you get time to check this?

**Comment by matfantinel** [comment]
@bbhtt sorry, no. I didn't feel comfortable releasing it because I can't test it locally anymore (didn't get the time to spin up a VM to run it).

But I guess that if the test build in this thread works well for you, I can merge it.

To be honest I need to find a new maintainer for Moneta 😥

**Pull request closed without merging**
